### ISSUE TITLE
Conversion to UEFI Fails

### ISSUE THREAD

**Issue by EdAChu** [mikeslattery/tunic#11]
Tried running tunic on Win 10, Version 10.0.18362.657
said conversion to UEFI was required, then fails on reboot

**Comment by EdAChu** [comment]
I have an old PC that predates UEFI, perhaps a message saying that UEFI instead of BIOS is required, and that conversion to UEFI on a system that doesn't support it won't work.

**Comment by mikeslattery** [comment]
Tunic [does the following](https://github.com/mikeslattery/tunic/blob/0.2.3/tunic.ps1#L194):
* If your computer doesn't support UEFI, it will say "UEFI required, but system cannot be convered".
* if your computer supports UEFI but isn't currently, it will say: "UEFI Required.  Conversion requires BIOS change during boot.  Convert from MBR to UEFI now?"

If you answer "Y", it will try to convert to EFI and reboot.  During the reboot you have to stop the boot (usually by repeatedly pressing an F-key), go into the firmware setttings, can change the boot type to (U)EFI, and then reboot again.   I called it "BIOS" because not everyone understands what "firmware" means.

Did it convert your hard drive?  Was your computer able to boot?  If not, did you go into the firmware and change the boot type to EFI?  You have suggestions on wording change?

In an earlier version, I didn't do the conversion but instead opened a [web page with instructions](https://www.windowscentral.com/how-convert-mbr-disk-gpt-move-bios-uefi-windows-10) on how to do it manually.  I may go back to that.

**Comment by EdAChu** [comment]
I got the message: "UEFI Required. Conversion requires BIOS change during
boot. Convert from MBR to UEFI now?"
but my BIOS is from 2009 and there's no option in the setup to choose the
boot type.
Dell M1330

**Comment by mikeslattery** [comment]
I think I'm going to remove the conversion feature.   I don't have enough control over the process to do a reliable conversion.   Instead, I'll work on eventual support for MBR.

By the way, I think the m1330 came with 2GB.  Tunic requires 4GB and always will.  (I can explain further if requested)

**Comment by EdAChu** [comment]
Yes, it probably did, but I put 4GB in mine. Also running the latest BIOS
version, A15. MBR would be nice.

**Comment by mikeslattery** [comment]
* 64 bit MBR to EFI conversion has been removed and replace with a how-to URL.
* #10 will supply support for MBR for 32 bit systems.
* 64 bit MBR is very rare and not even supported by Grub2 for Windows.  Supporting it is not worth the effort.  Users can convert manually if they want.
