### ISSUE TITLE
UEFI Win 10 1909 does not work

### ISSUE THREAD

**Issue by C0rn3j** [mikeslattery/tunic#2]
Using Tunic 0.2

Completely clean install of W10 Edu 1909 64-bit in a UEFI KVM VM does not work.

Used the `Erase entire disk` option, with every form using 'test' except for Computer name and Ubuntu 19.10.

The ISO downloads and computer simply reboots back into Windows normally, and nothing else happens.

**Comment by mikeslattery** [comment]
Thanks for the report.  I'll take a look in a few hours when I get home from work.
Would you mind trying Mint Cinnamon 19.3 and see if that works?

**Comment by C0rn3j** [comment]
Same thing with Mint.

**Comment by mikeslattery** [comment]
This "fix" broke other distros.

**Comment by mikeslattery** [comment]
The problem was that the grubx64.efi that comes with Ubuntu 19.10 has different hard-coded defaults than the one that comes with Mint 19.  Mint 19 uses Ubuntu 18.04's.

I believe @C0rn3j also had trouble with re-testing Mint because Tunic left some files behind from the Ubuntu 19.10 install attempt.

Sometime in the next few weeks I'll change to a consistent version of grub for the iso boot and ignore whatever comes with an iso.

**Comment by C0rn3j** [comment]
I still have the same issue with both 19.10 and Mint with the 0.2.1 release.
